// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeAzF_FddqM86O4RWchxL1gEgzdGtwqs8',
    appId: '1:877489159050:web:e897c8300d8579bfebe673',
    messagingSenderId: '877489159050',
    projectId: 'flutter-todoapp-435a9',
    authDomain: 'flutter-todoapp-435a9.firebaseapp.com',
    storageBucket: 'flutter-todoapp-435a9.appspot.com',
    measurementId: 'G-KBCE2PTF0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiid9c7Xb-QUGbsjXMYEcYEf7RSo-oedg',
    appId: '1:877489159050:android:0dc53476d7118656ebe673',
    messagingSenderId: '877489159050',
    projectId: 'flutter-todoapp-435a9',
    storageBucket: 'flutter-todoapp-435a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEd6I0zflEKVYravWAYi6uSTk48uQJWY',
    appId: '1:877489159050:ios:b7edb8f394a8539febe673',
    messagingSenderId: '877489159050',
    projectId: 'flutter-todoapp-435a9',
    storageBucket: 'flutter-todoapp-435a9.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKEd6I0zflEKVYravWAYi6uSTk48uQJWY',
    appId: '1:877489159050:ios:b7edb8f394a8539febe673',
    messagingSenderId: '877489159050',
    projectId: 'flutter-todoapp-435a9',
    storageBucket: 'flutter-todoapp-435a9.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeAzF_FddqM86O4RWchxL1gEgzdGtwqs8',
    appId: '1:877489159050:web:230de3f2c7e272e0ebe673',
    messagingSenderId: '877489159050',
    projectId: 'flutter-todoapp-435a9',
    authDomain: 'flutter-todoapp-435a9.firebaseapp.com',
    storageBucket: 'flutter-todoapp-435a9.appspot.com',
    measurementId: 'G-62B9QL3WCP',
  );
}
